### PR TITLE
Feature/new templates

### PR DESCRIPTION
**Pull request by hendriksoares**

### CODE REVIEW

**Comment by hendriksoares** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hendriksoares** [comment]
recheck

**Comment by hendrik-soares** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hendrik-soares** [comment]
recheck

**Review by gabriel-azion — APPROVED** [review]

**Review by Alquimar — APPROVED** [review]
LGTM!

**Pull request merged**
